### ISSUE TITLE
Wrong type inference in some cases?

### ISSUE THREAD

**Issue by reygoch** [haskelly-dev/Haskelly#37]
So, if I have this code :

```
main :: IO ()
main = putStrLn "some text"

-- or

main :: IO ()
main = do
    putStrLn "some text"

```

and  if I hover on `putStrLn` it gives me type of `IO ()` instead of `String -> IO ()`.

I'm not sure it's problem with Intero (although it might look like it is on the first glance).

**Comment by martrik** [comment]
Hey! Actually this is quite weird and I think it comes from Intero. In my case with version 0.4.20, if I try the first code it gives me the correct `String -> IO ()` but with the second example it just gives `IO ()`. Can this be related to the `do` keyboard?

**Comment by SelectricSimian** [comment]
I'm experiencing similar problems; even for a simple program, hovering gives incorrect type information for essentially every single expression.  The following isn't exactly a minimal example, but it does show many individual cases of things going wrong:

```Haskell
module Main where

facts :: [Integer]
facts = 1 : zipWith (*) [1..] facts

main :: IO ()
main = mapM_ (putStrLn . show) (take 10 (zip [0..] facts))
```

The only expressions in the above code for which the type info is **right** are `1`, `[1..]`, and `facts` in the definition of `facts`, and `mapM_` and `[0..]` in `main`.  However, even `1` and `mapM_` aren't *quite* right either, since they're too general for the context in which they're actually used.  `1` shows up as `Num t => t`, even though it really has to be `Integer`, and `mapM_` shows up as `(Monad m, Foldable t) => (a -> m b) -> t a -> m ()`, while it's really just `(Integer -> IO ()) -> [Integer] -> IO ()`.

Every other expression displays an incorrect type:

```Haskell
putStrLn :: (Integer, Integer) -> IO ()
show :: (Integer, Integer) -> IO ()
. :: (Integer, Integer) -> IO ()
take :: [(Integer, Integer)]
10 :: [(Integer, Integer)] -> [(Integer, Integer)] -- This one is especially mysterious
zip :: [(Integer, Integer)]
facts :: [(Integer, Integer)]
```

Oddly, this behavior seems to only appear after saving -- before saving, all the expressions have correct (but too general) types.

**Comment by martrik** [comment]
@SelectricSimian could you confirm that version 0.4.27 solves this problem?

**Comment by martrik** [comment]
We believe that these problems have been solved thanks to previous bug fixes so we proceed on closing this issue.
